server:
  port: 8222
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/bin/aircondition/mapper/xml/*.xml
spring:
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.33.108:3306/air_conditioner?serverTimezone=GMT%2B8
    data-username: root
    data-password: tian411328

  rabbitmq:
    host: 121.40.33.108
    port: 5672
    username: guest
    password: xidian
    virtual-host: /
    #1.开启 confirm 确认机制,确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #2.开启 return 确认机制    确认消息已发送到队列(Queue)
    publisher-returns: true
    #3.设置开启Mandatory,才能触发回调函数,无论消息推送结果怎么样都强制调用回调函数
    template:
      mandatory: true
    listener: #开启消费者进行重试
      simple:
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 20000ms
          initial-interval: 3000ms
#        acknowledge-mode: manual #开启手动ack
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
